/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/satellite': typeof SatelliteRoute
  '/sensors': typeof SensorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/satellite': typeof SatelliteRoute
  '/sensors': typeof SensorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/satellite': typeof SatelliteRoute
  '/sensors': typeof SensorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerts' | '/satellite' | '/sensors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/satellite' | '/sensors'
  id: '__root__' | '/' | '/alerts' | '/satellite' | '/sensors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  SatelliteRoute: typeof SatelliteRoute
  SensorsRoute: typeof SensorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  SatelliteRoute: SatelliteRoute,
  SensorsRoute: SensorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
